CLASS zamhcl_exr_hello_world DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

    METHODS hello RETURNING VALUE(result) TYPE string.
ENDCLASS.



CLASS ZAMHCL_EXR_HELLO_WORLD IMPLEMENTATION.


  METHOD hello.
    result = 'Hello, World!'.
  ENDMETHOD.
ENDCLASS.
